OPTION_SETS:
  yesno:
    - name: "Yes"
      value: true
    - name: "No"
      value: false
      negative: true

  consent:
    - name: "I agree"
      value: true
    - name: "I do not agree"
      value: false
      negative: true
  age:
    - name: "16 to 18"
      value: "16_18"
    - name: "19 to 24"
      value: "19_24"
    - name: "25 to 34"
      value: "25_34"
    - name: "35 to 44"
      value: "35_44"
    - name: "45 to 60"
      value: "45_60"
    - name: "Over 60"
      value: "over60"

  apple_attitude:
    - name: "Strongly Disagree"
      value: 0
    - name: "Disagree"
      value: 1
    - name: "Undecided"
      value: 2
    - name: "Agree"
      value: 3
    - name: "Strongly Agree"
      value: 4

  likelihood:
    - name: "Very unlikely"
      value: 0
    - name: "Unlikely"
      value: 1
    - name: "Likely"
      value: 3
    - name: "Very likely"
      value: 4


# MEASURES

# A single measure is a question and answer.

MEASURES:
  # pre questionnaire measures.

  # inclusion
  inclusion_intro:
    title: "Inclusion intro"
    text: "The particiant..."
    type: "info"

  inclusion1: 
    title: "Inclusion 1"
    text: "Is over 16 years of age"
    type: "radio"
    style: "horizontal flat"
    option_set: "yesno"
    mandatory:  true

  inclusion2:
    title: "Inclusion 1"
    text: "Is able to speak &amp; understand English "
    type: "radio"
    style: "horizontal flat"
    option_set: "yesno"
    mandatory: true

  inclusion3:
    title: "Inclusion 1"
    text: "Is capable of providing informed consent to participate"
    type: "radio"
    style: "horizontal flat"
    option_set: "yesno"
    mandatory: true

  inclusion4:
    title: "Inclusion 1"
    text: "Lives in the UK"
    type: "radio"
    style: "horizontal flat"
    option_set: "yesno"
    mandatory:  true

  inclusion5:
    title: "Inclusion 1"
    text: "Has <span class='text-danger'>NO</span> connection to the apple industry"
    type: "radio"
    style: "horizontal flat"
    option_set: "yesno"
    mandatory: true



#  consent
  consent1:
    title: "Consent 1"
    text: "I understand I will be asked questions about apples"
    type: "radio"
    style: "horizontal flat"
    option_set: "consent"

  consent2:
    title: "Consent 1"
    text: "I understand the purpose of this research"
    type: "radio"
    style: "horizontal flat"
    option_set: "consent"

  consent3:
    title: "Consent 1"
    text: "I have asked all the questions I want"
    type: "radio"
    style: "horizontal flat"
    option_set: "consent"

  consent4:
    title: "Consent 1"
    text: "I have had my questions answered in a way I understand"
    type: "radio"
    style: "horizontal flat"
    option_set: "consent"

  consent5:
    title: "Consent 1"
    text: "I understand it’s OK to stop taking part at any time"
    type: "radio"
    style: "horizontal flat"
    option_set: "consent"

  consent6:
    title: "Consent 1"
    text: "I am happy to take part in this research"
    type: "radio"
    style: "horizontal flat"
    option_set: "consent"


#  contact
  full_name:
    title: "Full name"
    text: "Full name"
    type: "string"
    style: "horizontal"
    mandatory: true

  email:
   title: "Email"
   text: "Email address"
   type: "string"
   style: "horizontal"
   mandatory: true

  mobile_number:
    title: "Mobile"
    text: "Mobile number"
    type: "telephone"
    style: "horizontal"
    mandatory: false

  home_telephone:
    title: "Home Phone Number"
    text: "Home phone number"
    type: "telephone"
    style: "horizontal"
    mandatory: false

# demographics
  gender:
    title: "Gender"
    text: "Are you"
    type: "radio"
    style: "float"
    options:
      - name: "Male"
        value: "m"
      - name: "Female"
        value: "f"
    mandatory: true

  age:
    title: "Age"
    text: "How old are you"
    type: "radio"
    style: "float"
    option_set: "age"
    mandatory: true

  employment_status:
    title: "Employment"
    text: "What is your current employment status"
    type: "select"
    options:
      - name: "Employed, working full-time"
        value: "full-time"
      - name: "Employed, working part-time"
        value: "part-time"
      - name: "Self Employed"
        value: "self"
      - name: "Unemployed"
        value: "unemployed"
      - name: "Student"
        value: "student"
      - name: "Retired"
        value: "retired"

# filter questions

  filter1:
    text: "Have you ever eaten an apple?"
    type: "radio"
    option_set: "yesno"
    style: "float"
    mandatory: true

  filter2:
    text: "Have you eaten an apple in the past 6 months</strong>?"
    type: "radio"
    option_set: "yesno"
    style: "float"
    mandatory: true
    visible_if: "filter2_visible"

  past24:
    text: "Have you eaten an apple in the <strong>past 24 hours?</strong>"
    type: "radio"
    option_set: "yesno"
    style: "float"
    visible_if:  "past24_visible"

  pasthour:
    text: "Have you eaten an aple within the last hour?"
    type: "radio"
    option_set: "yesno"
    style: "float"
    visible_if:  "past_hour_visibe"

  age_first:
    text: "How old were you when you ate your first apple"
    type: "radio"
    style:  "flat"
    options:
      - name: "under 5"
        value: "under5"
      - name: "5 to 10"
        value: "5-10"
      - name: "11 to 15"
        value: "11-15"
      - name: "16 to 18"
        value:  "16_18"
      - name: "19 to 24"
        value:  "19_24"
      - name: "25 to 34"
        value:  "25_34"
      - name: "35 to 44"
        value:  "35_44"
      - name: "45 to 60"
        value:  "45_60"
      - name:  "Over 60"
        value:  "over60"
    option_filter: "age_first_filter"

# apple_frequency

  apple_frequency_1:
    text: "Over the past 6 months, how often have you eaten an apple?"
    type: "radio"
    style: "float"
    mandatory: true
    options:
      - name: "Never<br />&nbsp;"
        value: 0
      - name: "Monthly<br />&nbsp;"
        value: 1
      - name: "2 to 4 times<br /> a month"
        value: 2
      - name: "2 to 3 times<br /> a week"
        value: 3
      - name: "4 or more times<br /> a week"
        value: 4

  apple_frequency_2:
    text: "How many apples do you eat on a typical day you are eating apples?"
    type: "radio"
    style: "float"
    mandatory: true
    options:
      - name: "1 to 2"
        value: 0
      - name: "3 to 4"
        value: 1
      - name: "5 to 6"
        value: 2
      - name: "7 to 9"
        value: 3
      - name: "more than 10"
        value: 4

  apple_frequency_3:
    text: "How many times have you had 3 or more apples in a single day in the past 6 months?"
    type: "radio"
    style: "float"
    mandatory: true
    options:
      - name: "Never"
        value: 0
      - name: "Less than monthly"
        value: 1
      - name: "Monthly"
        value: 2
      - name: "Weekly"
        value: 3
      - name: "Daily or almost daily"
        value: 4
# apple_attitude

  apple_attitude_1:
    text: "I find apples tasty"
    type: "radio"
    style: "float"
    option_set: "apple_attitude"


  apple_attitude_2:
    text: "I find it hard to eat an apple"
    type: "radio"
    style: "float"
    option_set: "apple_attitude"


  apple_attitude_3:
    text: "I will eat an apple as a snack between meals"
    type: "radio"
    style: "float"
    option_set: "apple_attitude"


  apple_attitude_4:
    text: "I take a long time to eat a whole apple"
    type: "radio"
    style: "float"
    option_set: "apple_attitude"


  apple_attitude_5:
    text: "I always include apples in my groceries"
    type: "radio"
    style: "float"
    option_set: "apple_attitude"


  apple_attitude_6:
    text: "I eat apples because they are good for me"
    type: "radio"
    style: "float"
    option_set: "apple_attitude"

# apple_likelihood

  apple_likelihood_1:
    text: "I will regret eating an apple"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_likelihood_2:
    text: "I will offer an apple to someone"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_likelihood_3:
    text: "I will discuss apples with someone"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_likelihood_4:
    text: "I will wish I had an apple when one isn't available"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_likelihood_5:
    text: "I will try to resist an apple"
    type: "radio"
    style: "float"
    option_set: "likelihood"

# apple association
  apple_association:
    text: "Which of the following do you most associate with the word <strong>Apple</strong>"
    type: "radio"
    style: "flat"
    options:
      - name: "A fruit"
        value: "fruit"
      - name: "A tree"
        value: "tree"
      - name: "A technology corporation (Macs, iPhones, etc.)"
        value: "computer"
      - name: "A multimedia corporation (The Beatles)"
        value: "beatles"
      - name: "A Singer Songwriter (Fiona Apple)"
        value: "singer"
      - name: "Other"
        value: "other"

  apple_association_other:
    text: "Please specify"
    type: "string"
    style: "horizontal"
    visible_if: apple_association_other_visible

# apple_general_attitude

  apple_phrases_1:
    text: "An apple a day keeps the doctor away"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_phrases_2:
    text: "The apple doesn't fall far from the tree"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_phrases_3:
    text: "The apple of my eye"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_phrases_4:
    text: "How do you like them apples"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_phrases_5:
    text: "Upset the applecart"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_phrases_6:
    text: "A bad apple"
    type: "radio"
    style: "float"
    option_set: "likelihood"

  apple_meter:
    text: "This scale is numbered from 0 to 100. 100 means the apples are the most important thing to you, and 0 means they have no importance. Please choose a number that represents how important apples are to you."
    type: "slider" 
